name: 🐛 Self-hoster instance bug Report
description: File a bug report related specifically to a self-hosted instance
title: "🐛 Bug (Self-host): "
labels: ["bug"]
assignees:
  - reishimanfr
body:
  - type: dropdown
    attributes:
      label: "What platform are you hosting on?"
      options:
        - Windows
        - Linux
        - MacOS 
        - Other (Specify in additional context)
    validations:
      required: true

  - type: input
      label: "What version of Lavalink are you using?"
      description: "You can check the Lavalink version by running the jar file and checking logs."
    validations:
      required: true

  - type: input
    attributes:
      label: "What version of your runtime are you using"
      description: "Type `node --version` in your terminal and paste it here
    validations:
      required: true

  - type: input
    attributes:
      label: "Describe the bug"
      description: "Provide a small description for the bug you're facing"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Provide the steps to reproduce the bug"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Additional context and info"
      description: "Provide any additional context or info regarding the issue, if applicable include screenshots."
