name: Publish to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: |
          docker build . -t reishimanfr/the-world-machine:latest

      - name: publish
        run: |
          docker push reishimanfr/the-world-machine:latest
